# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_first_name', models.CharField(max_length=255)),
                ('author_last_name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField()),
                ('users', models.ManyToManyField(related_name='books', to='users.User')),
            ],
        ),
    ]
